# -*- coding: utf-8 -*-
"""ExercíciosPY4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KbWr0rcYbLBwzBQ7gRQAufNc4sJD7PRr
"""

texto = "Eduardo Noranha da Silva Matos"
comprimento = len(texto)
print(comprimento)

x = 'oi'
tipo = type (x)
print(tipo)

texto = 'Duduzinho'
lista = list(texto)
print (lista)

numeros = range(1 , 14)

print(numeros)

numeros = (1,2,3,12,5123,6132,12)
soma =sum(numeros)

print(soma)

numeros = (12,1,23,4,5,63,9,0)

minimo = min(numeros)
maximo = max(numeros)

print(minimo,maximo)

numeros = (12,1,23,4,5,63,9,0)
numeros_ordenados = sorted(numeros)
print(numeros_ordenados)